name: CI/CD Pipeline for holamundo_multi
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv # Asegura extensiones b치sicas

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH/Rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Configuraci칩n segura del agente SSH
          mkdir -p ~/.ssh
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

          # Sincronizaci칩n de archivos (excluimos lo innecesario)
          rsync -avz --delete \
            --exclude '.git*' \
            --exclude 'tests' \
            --exclude 'phpunit.xml' \
            . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.DEPLOY_PATH }}

          # Comandos remotos
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}
            composer install --no-dev --optimize-autoloader --no-interaction
            # Intentar reiniciar apache (requiere configuraci칩n NOPASSWD en el server)
            sudo systemctl restart apache2
          EOF